services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
  gateway:
    build: {context: ., args: { SERVICE: gateway }}
    ports:
      - "8000:8000"
